# Generated by Django 4.0.6 on 2023-05-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text_game', models.TextField(blank=True, null=True)),
                ('link_game', models.TextField(blank=True, null=True)),
                ('name_game', models.TextField(blank=True, null=True)),
                ('img_game', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'games',
                'managed': False,
            },
        ),
         migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('text_blog', models.TextField(blank=True, null=True)),
                ('img_blog', models.TextField(blank=True, null=True)),
                ('video_blog', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_game', models.TextField(blank=True, null=True)),
                ('video_game', models.TextField(blank=True, null=True)),
                ('text_game', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
    ]
